platform :ios, '9.0'

target '19.Todoey' do

  use_frameworks!

  # Pods for 19.Todoey
  
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  

end
